Convert new line chars into html break tags
TheBeyondGroup/shopify-rich-text-renderer pull request #15
Opened 2023-11-28 16:56 UTC by richardscarrott

Thanks for the library, it's been very helpful 👍

We've found Shopify's rich text editor returns new line characters within text nodes which HTML ignores. This PR therefore converts them to break tags so the html renders more similarly to the editor UI.

2024-04-08 22:11 UTC, jeffreyguenther commented
@richardscarrott Thanks for the PR! We'll be reviewing it shortly!

2024-04-09 00:09 UTC, mcqua007 requested changes
First things first, we really appreciate you leaving feedback and what's more proposing an addition :) . After careful consideration and discussing the change with the team internally we would like to include this change behind an option flag called `convertNewlineToLineBreak` where it defaults to false. We thought it better to have this addition opt-in as to to break any styles or structure of anyone currently using the package. Please let me know if you have any questions!

2024-04-09 00:09 UTC, mcqua007 commented on src/index.js
> +  const value = el?.value?.replace(/\n/g, '<br>')
Can you render it as a self closing tag, i.e. `<br />` ?

2024-05-30 17:44 UTC, jeffreyguenther commented
Closing this PR as we're adding this feature in #17

2024-05-30 17:44 UTC, closed without merging